### ISSUE TITLE
Weekly React Digest

### ISSUE THREAD

**Issue by jakubgarfield** [ericdouglas/react-roadmap#1]
Add this weekly newsletter to the additional resources section as it might be useful to keep up to date about resources like this :). It selects top 5 links and sends them to your inbox every Monday morning. Check it out at [Weekly React Digest](http://reactdigest.net/).

**Comment by ericdouglas** [comment]
@jakubgarfield thanks for your suggestion! 

I just found some additional links that I'll add and one of them includes the Weekly React Digest. I'll make the update ASAP.

Links to be added:

- https://github.com/markerikson/react-redux-links
- https://github.com/markerikson/react-redux-links/blob/master/community-resources.md
- https://github.com/markerikson/redux-ecosystem-links
