### ISSUE TITLE
Adding typescript section

### ISSUE THREAD

**Issue by brauliodiez** [ericdouglas/react-roadmap#4]
I think it would be a good idea to add a react + typescript section (there is a good community of typescript developers and in some cases some tweaking is needed to integrate it on a React project).

Material proposal:

- [TypeScript Deep Dive](https://www.gitbook.com/book/basarat/typescript/details): great free Git Book to get started with typescript.
- [React TODO app Typescript](https://github.com/jaysoo/todomvc-redux-react-typescript): Typescript migrated version of tthe javascript React TODO sample 
- [React Typescript Samples](https://github.com/Lemoncode/react-typescript-samples): 18 samples covering topics from the base (create an empty project) to advanced ones (thunk, saga, middleware, hot loading).

**Comment by ericdouglas** [comment]
@brauliodiez thank you so much for your suggestion!

A lot of people approved your suggestion, so we should add a TypeScript section in our roadmap.

Can you submit a PR adding those TypeScript resources in the [Optional Path](https://github.com/ericdouglas/react-roadmap#optional-path) section?!

**Comment by brauliodiez** [comment]
Thanks ! Going to start working on that right now :)
